package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TPortalEmailConfig;
import com.vccloud.portal.db.model.TPortalEmailConfigExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TPortalEmailConfigDAOImpl extends SqlMapClientDaoSupport implements TPortalEmailConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public TPortalEmailConfigDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int countByExample(TPortalEmailConfigExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_portal_email_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int deleteByExample(TPortalEmailConfigExample example) {
        int rows = getSqlMapClientTemplate().delete("t_portal_email_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int deleteByPrimaryKey(Long id) {
        TPortalEmailConfig key = new TPortalEmailConfig();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_portal_email_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public Long insert(TPortalEmailConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("t_portal_email_config.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public Long insertSelective(TPortalEmailConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("t_portal_email_config.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public List selectByExample(TPortalEmailConfigExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_portal_email_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public TPortalEmailConfig selectByPrimaryKey(Long id) {
        TPortalEmailConfig key = new TPortalEmailConfig();
        key.setId(id);
        TPortalEmailConfig record = (TPortalEmailConfig) getSqlMapClientTemplate().queryForObject("t_portal_email_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int updateByExampleSelective(TPortalEmailConfig record, TPortalEmailConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_portal_email_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int updateByExample(TPortalEmailConfig record, TPortalEmailConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_portal_email_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int updateByPrimaryKeySelective(TPortalEmailConfig record) {
        int rows = getSqlMapClientTemplate().update("t_portal_email_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public int updateByPrimaryKey(TPortalEmailConfig record) {
        int rows = getSqlMapClientTemplate().update("t_portal_email_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private static class UpdateByExampleParms extends TPortalEmailConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, TPortalEmailConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}