package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TPortalEmailConfig;
import com.vccloud.portal.db.model.TPortalEmailConfigExample;
import java.util.List;

public interface TPortalEmailConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int countByExample(TPortalEmailConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int deleteByExample(TPortalEmailConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    Long insert(TPortalEmailConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    Long insertSelective(TPortalEmailConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    List selectByExample(TPortalEmailConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    TPortalEmailConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int updateByExampleSelective(TPortalEmailConfig record, TPortalEmailConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int updateByExample(TPortalEmailConfig record, TPortalEmailConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int updateByPrimaryKeySelective(TPortalEmailConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    int updateByPrimaryKey(TPortalEmailConfig record);
}