package com.vccloud.portal.db.dao;

import java.util.Date;
import java.util.List;

import com.vccloud.portal.db.model.TReport;
import com.vccloud.portal.db.model.TReportExample;

public interface TReportDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int countByExample(TReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int deleteByExample(TReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    Long insert(TReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    Long insertSelective(TReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    List selectByExample(TReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    TReport selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int updateByExampleSelective(TReport record, TReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int updateByExample(TReport record, TReportExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    int updateByPrimaryKeySelective(TReport record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
	int updateByPrimaryKey(TReport record);

	public Date getLatestImportTime(long portalId);
}