package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TReport;
import com.vccloud.portal.db.model.TReportExample;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TReportDAOImpl extends SqlMapClientDaoSupport implements TReportDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public TReportDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int countByExample(TReportExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_report.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int deleteByExample(TReportExample example) {
        int rows = getSqlMapClientTemplate().delete("t_report.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int deleteByPrimaryKey(Long id) {
        TReport key = new TReport();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_report.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long insert(TReport record) {
        Object newKey = getSqlMapClientTemplate().insert("t_report.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long insertSelective(TReport record) {
        Object newKey = getSqlMapClientTemplate().insert("t_report.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public List selectByExample(TReportExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_report.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public TReport selectByPrimaryKey(Long id) {
        TReport key = new TReport();
        key.setId(id);
        TReport record = (TReport) getSqlMapClientTemplate().queryForObject("t_report.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int updateByExampleSelective(TReport record, TReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_report.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int updateByExample(TReport record, TReportExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_report.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int updateByPrimaryKeySelective(TReport record) {
        int rows = getSqlMapClientTemplate().update("t_report.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public int updateByPrimaryKey(TReport record) {
        int rows = getSqlMapClientTemplate().update("t_report.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private static class UpdateByExampleParms extends TReportExample {
        private Object record;

        public UpdateByExampleParms(Object record, TReportExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
	}

	public Date getLatestImportTime(long portalId) {
		Map params = new HashMap();
		params.put("portalId", portalId);
		Date date = (Date) getSqlMapClientTemplate().queryForObject(
				"t_report.getLatestImportTime", params);
		return date;
	}
}