package com.vccloud.portal.db.model;

public class TPortalEmailConfig {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.id
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.portal_url
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private String portalUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.host
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private String host;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.port
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private String port;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.email
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_portal_email_config.password
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    private String password;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.id
     *
     * @return the value of t_portal_email_config.id
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.id
     *
     * @param id the value for t_portal_email_config.id
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.portal_url
     *
     * @return the value of t_portal_email_config.portal_url
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getPortalUrl() {
        return portalUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.portal_url
     *
     * @param portalUrl the value for t_portal_email_config.portal_url
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setPortalUrl(String portalUrl) {
        this.portalUrl = portalUrl == null ? null : portalUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.host
     *
     * @return the value of t_portal_email_config.host
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.host
     *
     * @param host the value for t_portal_email_config.host
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.port
     *
     * @return the value of t_portal_email_config.port
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.port
     *
     * @param port the value for t_portal_email_config.port
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.email
     *
     * @return the value of t_portal_email_config.email
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.email
     *
     * @param email the value for t_portal_email_config.email
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_portal_email_config.password
     *
     * @return the value of t_portal_email_config.password
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_portal_email_config.password
     *
     * @param password the value for t_portal_email_config.password
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}