package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TPortalEmailConfigExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public TPortalEmailConfigExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    protected TPortalEmailConfigExample(TPortalEmailConfigExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_portal_email_config
     *
     * @ibatorgenerated Wed Feb 19 16:20:21 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andPortalUrlIsNull() {
            addCriterion("portal_url is null");
            return this;
        }

        public Criteria andPortalUrlIsNotNull() {
            addCriterion("portal_url is not null");
            return this;
        }

        public Criteria andPortalUrlEqualTo(String value) {
            addCriterion("portal_url =", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlNotEqualTo(String value) {
            addCriterion("portal_url <>", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlGreaterThan(String value) {
            addCriterion("portal_url >", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlGreaterThanOrEqualTo(String value) {
            addCriterion("portal_url >=", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlLessThan(String value) {
            addCriterion("portal_url <", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlLessThanOrEqualTo(String value) {
            addCriterion("portal_url <=", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlLike(String value) {
            addCriterion("portal_url like", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlNotLike(String value) {
            addCriterion("portal_url not like", value, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlIn(List values) {
            addCriterion("portal_url in", values, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlNotIn(List values) {
            addCriterion("portal_url not in", values, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlBetween(String value1, String value2) {
            addCriterion("portal_url between", value1, value2, "portalUrl");
            return this;
        }

        public Criteria andPortalUrlNotBetween(String value1, String value2) {
            addCriterion("portal_url not between", value1, value2, "portalUrl");
            return this;
        }

        public Criteria andHostIsNull() {
            addCriterion("host is null");
            return this;
        }

        public Criteria andHostIsNotNull() {
            addCriterion("host is not null");
            return this;
        }

        public Criteria andHostEqualTo(String value) {
            addCriterion("host =", value, "host");
            return this;
        }

        public Criteria andHostNotEqualTo(String value) {
            addCriterion("host <>", value, "host");
            return this;
        }

        public Criteria andHostGreaterThan(String value) {
            addCriterion("host >", value, "host");
            return this;
        }

        public Criteria andHostGreaterThanOrEqualTo(String value) {
            addCriterion("host >=", value, "host");
            return this;
        }

        public Criteria andHostLessThan(String value) {
            addCriterion("host <", value, "host");
            return this;
        }

        public Criteria andHostLessThanOrEqualTo(String value) {
            addCriterion("host <=", value, "host");
            return this;
        }

        public Criteria andHostLike(String value) {
            addCriterion("host like", value, "host");
            return this;
        }

        public Criteria andHostNotLike(String value) {
            addCriterion("host not like", value, "host");
            return this;
        }

        public Criteria andHostIn(List values) {
            addCriterion("host in", values, "host");
            return this;
        }

        public Criteria andHostNotIn(List values) {
            addCriterion("host not in", values, "host");
            return this;
        }

        public Criteria andHostBetween(String value1, String value2) {
            addCriterion("host between", value1, value2, "host");
            return this;
        }

        public Criteria andHostNotBetween(String value1, String value2) {
            addCriterion("host not between", value1, value2, "host");
            return this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return this;
        }

        public Criteria andPortEqualTo(String value) {
            addCriterion("port =", value, "port");
            return this;
        }

        public Criteria andPortNotEqualTo(String value) {
            addCriterion("port <>", value, "port");
            return this;
        }

        public Criteria andPortGreaterThan(String value) {
            addCriterion("port >", value, "port");
            return this;
        }

        public Criteria andPortGreaterThanOrEqualTo(String value) {
            addCriterion("port >=", value, "port");
            return this;
        }

        public Criteria andPortLessThan(String value) {
            addCriterion("port <", value, "port");
            return this;
        }

        public Criteria andPortLessThanOrEqualTo(String value) {
            addCriterion("port <=", value, "port");
            return this;
        }

        public Criteria andPortLike(String value) {
            addCriterion("port like", value, "port");
            return this;
        }

        public Criteria andPortNotLike(String value) {
            addCriterion("port not like", value, "port");
            return this;
        }

        public Criteria andPortIn(List values) {
            addCriterion("port in", values, "port");
            return this;
        }

        public Criteria andPortNotIn(List values) {
            addCriterion("port not in", values, "port");
            return this;
        }

        public Criteria andPortBetween(String value1, String value2) {
            addCriterion("port between", value1, value2, "port");
            return this;
        }

        public Criteria andPortNotBetween(String value1, String value2) {
            addCriterion("port not between", value1, value2, "port");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return this;
        }
    }
}