package com.vccloud.portal.db.model;

import java.util.Date;

public class TReport {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.portal_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long portalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.tenant_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long tenantId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.date
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Date date;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.year
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long year;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.month
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long month;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.week
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long week;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.day
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.hour
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long hour;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.quarter_1
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long quarter1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.quarter_2
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long quarter2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.quarter_3
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long quarter3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_report.quarter_4
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    private Long quarter4;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.id
     *
     * @return the value of t_report.id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.id
     *
     * @param id the value for t_report.id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.portal_id
     *
     * @return the value of t_report.portal_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getPortalId() {
        return portalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.portal_id
     *
     * @param portalId the value for t_report.portal_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setPortalId(Long portalId) {
        this.portalId = portalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.tenant_id
     *
     * @return the value of t_report.tenant_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.tenant_id
     *
     * @param tenantId the value for t_report.tenant_id
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.date
     *
     * @return the value of t_report.date
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.date
     *
     * @param date the value for t_report.date
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.year
     *
     * @return the value of t_report.year
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getYear() {
        return year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.year
     *
     * @param year the value for t_report.year
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setYear(Long year) {
        this.year = year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.month
     *
     * @return the value of t_report.month
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getMonth() {
        return month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.month
     *
     * @param month the value for t_report.month
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setMonth(Long month) {
        this.month = month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.week
     *
     * @return the value of t_report.week
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getWeek() {
        return week;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.week
     *
     * @param week the value for t_report.week
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setWeek(Long week) {
        this.week = week;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.day
     *
     * @return the value of t_report.day
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.day
     *
     * @param day the value for t_report.day
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setDay(Long day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.hour
     *
     * @return the value of t_report.hour
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getHour() {
        return hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.hour
     *
     * @param hour the value for t_report.hour
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setHour(Long hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.quarter_1
     *
     * @return the value of t_report.quarter_1
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getQuarter1() {
        return quarter1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.quarter_1
     *
     * @param quarter1 the value for t_report.quarter_1
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setQuarter1(Long quarter1) {
        this.quarter1 = quarter1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.quarter_2
     *
     * @return the value of t_report.quarter_2
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getQuarter2() {
        return quarter2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.quarter_2
     *
     * @param quarter2 the value for t_report.quarter_2
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setQuarter2(Long quarter2) {
        this.quarter2 = quarter2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.quarter_3
     *
     * @return the value of t_report.quarter_3
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getQuarter3() {
        return quarter3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.quarter_3
     *
     * @param quarter3 the value for t_report.quarter_3
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setQuarter3(Long quarter3) {
        this.quarter3 = quarter3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_report.quarter_4
     *
     * @return the value of t_report.quarter_4
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Long getQuarter4() {
        return quarter4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_report.quarter_4
     *
     * @param quarter4 the value for t_report.quarter_4
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setQuarter4(Long quarter4) {
        this.quarter4 = quarter4;
    }
}