package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TReportExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public TReportExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    protected TReportExample(TReportExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_report
     *
     * @ibatorgenerated Tue Feb 18 14:28:36 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andPortalIdIsNull() {
            addCriterion("portal_id is null");
            return this;
        }

        public Criteria andPortalIdIsNotNull() {
            addCriterion("portal_id is not null");
            return this;
        }

        public Criteria andPortalIdEqualTo(Long value) {
            addCriterion("portal_id =", value, "portalId");
            return this;
        }

        public Criteria andPortalIdNotEqualTo(Long value) {
            addCriterion("portal_id <>", value, "portalId");
            return this;
        }

        public Criteria andPortalIdGreaterThan(Long value) {
            addCriterion("portal_id >", value, "portalId");
            return this;
        }

        public Criteria andPortalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("portal_id >=", value, "portalId");
            return this;
        }

        public Criteria andPortalIdLessThan(Long value) {
            addCriterion("portal_id <", value, "portalId");
            return this;
        }

        public Criteria andPortalIdLessThanOrEqualTo(Long value) {
            addCriterion("portal_id <=", value, "portalId");
            return this;
        }

        public Criteria andPortalIdIn(List values) {
            addCriterion("portal_id in", values, "portalId");
            return this;
        }

        public Criteria andPortalIdNotIn(List values) {
            addCriterion("portal_id not in", values, "portalId");
            return this;
        }

        public Criteria andPortalIdBetween(Long value1, Long value2) {
            addCriterion("portal_id between", value1, value2, "portalId");
            return this;
        }

        public Criteria andPortalIdNotBetween(Long value1, Long value2) {
            addCriterion("portal_id not between", value1, value2, "portalId");
            return this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return this;
        }

        public Criteria andTenantIdIn(List values) {
            addCriterion("tenant_id in", values, "tenantId");
            return this;
        }

        public Criteria andTenantIdNotIn(List values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return this;
        }

        public Criteria andDateIn(List values) {
            addCriterion("date in", values, "date");
            return this;
        }

        public Criteria andDateNotIn(List values) {
            addCriterion("date not in", values, "date");
            return this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return this;
        }

        public Criteria andYearEqualTo(Long value) {
            addCriterion("year =", value, "year");
            return this;
        }

        public Criteria andYearNotEqualTo(Long value) {
            addCriterion("year <>", value, "year");
            return this;
        }

        public Criteria andYearGreaterThan(Long value) {
            addCriterion("year >", value, "year");
            return this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Long value) {
            addCriterion("year >=", value, "year");
            return this;
        }

        public Criteria andYearLessThan(Long value) {
            addCriterion("year <", value, "year");
            return this;
        }

        public Criteria andYearLessThanOrEqualTo(Long value) {
            addCriterion("year <=", value, "year");
            return this;
        }

        public Criteria andYearIn(List values) {
            addCriterion("year in", values, "year");
            return this;
        }

        public Criteria andYearNotIn(List values) {
            addCriterion("year not in", values, "year");
            return this;
        }

        public Criteria andYearBetween(Long value1, Long value2) {
            addCriterion("year between", value1, value2, "year");
            return this;
        }

        public Criteria andYearNotBetween(Long value1, Long value2) {
            addCriterion("year not between", value1, value2, "year");
            return this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return this;
        }

        public Criteria andMonthEqualTo(Long value) {
            addCriterion("month =", value, "month");
            return this;
        }

        public Criteria andMonthNotEqualTo(Long value) {
            addCriterion("month <>", value, "month");
            return this;
        }

        public Criteria andMonthGreaterThan(Long value) {
            addCriterion("month >", value, "month");
            return this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(Long value) {
            addCriterion("month >=", value, "month");
            return this;
        }

        public Criteria andMonthLessThan(Long value) {
            addCriterion("month <", value, "month");
            return this;
        }

        public Criteria andMonthLessThanOrEqualTo(Long value) {
            addCriterion("month <=", value, "month");
            return this;
        }

        public Criteria andMonthIn(List values) {
            addCriterion("month in", values, "month");
            return this;
        }

        public Criteria andMonthNotIn(List values) {
            addCriterion("month not in", values, "month");
            return this;
        }

        public Criteria andMonthBetween(Long value1, Long value2) {
            addCriterion("month between", value1, value2, "month");
            return this;
        }

        public Criteria andMonthNotBetween(Long value1, Long value2) {
            addCriterion("month not between", value1, value2, "month");
            return this;
        }

        public Criteria andWeekIsNull() {
            addCriterion("week is null");
            return this;
        }

        public Criteria andWeekIsNotNull() {
            addCriterion("week is not null");
            return this;
        }

        public Criteria andWeekEqualTo(Long value) {
            addCriterion("week =", value, "week");
            return this;
        }

        public Criteria andWeekNotEqualTo(Long value) {
            addCriterion("week <>", value, "week");
            return this;
        }

        public Criteria andWeekGreaterThan(Long value) {
            addCriterion("week >", value, "week");
            return this;
        }

        public Criteria andWeekGreaterThanOrEqualTo(Long value) {
            addCriterion("week >=", value, "week");
            return this;
        }

        public Criteria andWeekLessThan(Long value) {
            addCriterion("week <", value, "week");
            return this;
        }

        public Criteria andWeekLessThanOrEqualTo(Long value) {
            addCriterion("week <=", value, "week");
            return this;
        }

        public Criteria andWeekIn(List values) {
            addCriterion("week in", values, "week");
            return this;
        }

        public Criteria andWeekNotIn(List values) {
            addCriterion("week not in", values, "week");
            return this;
        }

        public Criteria andWeekBetween(Long value1, Long value2) {
            addCriterion("week between", value1, value2, "week");
            return this;
        }

        public Criteria andWeekNotBetween(Long value1, Long value2) {
            addCriterion("week not between", value1, value2, "week");
            return this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return this;
        }

        public Criteria andDayEqualTo(Long value) {
            addCriterion("day =", value, "day");
            return this;
        }

        public Criteria andDayNotEqualTo(Long value) {
            addCriterion("day <>", value, "day");
            return this;
        }

        public Criteria andDayGreaterThan(Long value) {
            addCriterion("day >", value, "day");
            return this;
        }

        public Criteria andDayGreaterThanOrEqualTo(Long value) {
            addCriterion("day >=", value, "day");
            return this;
        }

        public Criteria andDayLessThan(Long value) {
            addCriterion("day <", value, "day");
            return this;
        }

        public Criteria andDayLessThanOrEqualTo(Long value) {
            addCriterion("day <=", value, "day");
            return this;
        }

        public Criteria andDayIn(List values) {
            addCriterion("day in", values, "day");
            return this;
        }

        public Criteria andDayNotIn(List values) {
            addCriterion("day not in", values, "day");
            return this;
        }

        public Criteria andDayBetween(Long value1, Long value2) {
            addCriterion("day between", value1, value2, "day");
            return this;
        }

        public Criteria andDayNotBetween(Long value1, Long value2) {
            addCriterion("day not between", value1, value2, "day");
            return this;
        }

        public Criteria andHourIsNull() {
            addCriterion("hour is null");
            return this;
        }

        public Criteria andHourIsNotNull() {
            addCriterion("hour is not null");
            return this;
        }

        public Criteria andHourEqualTo(Long value) {
            addCriterion("hour =", value, "hour");
            return this;
        }

        public Criteria andHourNotEqualTo(Long value) {
            addCriterion("hour <>", value, "hour");
            return this;
        }

        public Criteria andHourGreaterThan(Long value) {
            addCriterion("hour >", value, "hour");
            return this;
        }

        public Criteria andHourGreaterThanOrEqualTo(Long value) {
            addCriterion("hour >=", value, "hour");
            return this;
        }

        public Criteria andHourLessThan(Long value) {
            addCriterion("hour <", value, "hour");
            return this;
        }

        public Criteria andHourLessThanOrEqualTo(Long value) {
            addCriterion("hour <=", value, "hour");
            return this;
        }

        public Criteria andHourIn(List values) {
            addCriterion("hour in", values, "hour");
            return this;
        }

        public Criteria andHourNotIn(List values) {
            addCriterion("hour not in", values, "hour");
            return this;
        }

        public Criteria andHourBetween(Long value1, Long value2) {
            addCriterion("hour between", value1, value2, "hour");
            return this;
        }

        public Criteria andHourNotBetween(Long value1, Long value2) {
            addCriterion("hour not between", value1, value2, "hour");
            return this;
        }

        public Criteria andQuarter1IsNull() {
            addCriterion("quarter_1 is null");
            return this;
        }

        public Criteria andQuarter1IsNotNull() {
            addCriterion("quarter_1 is not null");
            return this;
        }

        public Criteria andQuarter1EqualTo(Long value) {
            addCriterion("quarter_1 =", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1NotEqualTo(Long value) {
            addCriterion("quarter_1 <>", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1GreaterThan(Long value) {
            addCriterion("quarter_1 >", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1GreaterThanOrEqualTo(Long value) {
            addCriterion("quarter_1 >=", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1LessThan(Long value) {
            addCriterion("quarter_1 <", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1LessThanOrEqualTo(Long value) {
            addCriterion("quarter_1 <=", value, "quarter1");
            return this;
        }

        public Criteria andQuarter1In(List values) {
            addCriterion("quarter_1 in", values, "quarter1");
            return this;
        }

        public Criteria andQuarter1NotIn(List values) {
            addCriterion("quarter_1 not in", values, "quarter1");
            return this;
        }

        public Criteria andQuarter1Between(Long value1, Long value2) {
            addCriterion("quarter_1 between", value1, value2, "quarter1");
            return this;
        }

        public Criteria andQuarter1NotBetween(Long value1, Long value2) {
            addCriterion("quarter_1 not between", value1, value2, "quarter1");
            return this;
        }

        public Criteria andQuarter2IsNull() {
            addCriterion("quarter_2 is null");
            return this;
        }

        public Criteria andQuarter2IsNotNull() {
            addCriterion("quarter_2 is not null");
            return this;
        }

        public Criteria andQuarter2EqualTo(Long value) {
            addCriterion("quarter_2 =", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2NotEqualTo(Long value) {
            addCriterion("quarter_2 <>", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2GreaterThan(Long value) {
            addCriterion("quarter_2 >", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2GreaterThanOrEqualTo(Long value) {
            addCriterion("quarter_2 >=", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2LessThan(Long value) {
            addCriterion("quarter_2 <", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2LessThanOrEqualTo(Long value) {
            addCriterion("quarter_2 <=", value, "quarter2");
            return this;
        }

        public Criteria andQuarter2In(List values) {
            addCriterion("quarter_2 in", values, "quarter2");
            return this;
        }

        public Criteria andQuarter2NotIn(List values) {
            addCriterion("quarter_2 not in", values, "quarter2");
            return this;
        }

        public Criteria andQuarter2Between(Long value1, Long value2) {
            addCriterion("quarter_2 between", value1, value2, "quarter2");
            return this;
        }

        public Criteria andQuarter2NotBetween(Long value1, Long value2) {
            addCriterion("quarter_2 not between", value1, value2, "quarter2");
            return this;
        }

        public Criteria andQuarter3IsNull() {
            addCriterion("quarter_3 is null");
            return this;
        }

        public Criteria andQuarter3IsNotNull() {
            addCriterion("quarter_3 is not null");
            return this;
        }

        public Criteria andQuarter3EqualTo(Long value) {
            addCriterion("quarter_3 =", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3NotEqualTo(Long value) {
            addCriterion("quarter_3 <>", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3GreaterThan(Long value) {
            addCriterion("quarter_3 >", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3GreaterThanOrEqualTo(Long value) {
            addCriterion("quarter_3 >=", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3LessThan(Long value) {
            addCriterion("quarter_3 <", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3LessThanOrEqualTo(Long value) {
            addCriterion("quarter_3 <=", value, "quarter3");
            return this;
        }

        public Criteria andQuarter3In(List values) {
            addCriterion("quarter_3 in", values, "quarter3");
            return this;
        }

        public Criteria andQuarter3NotIn(List values) {
            addCriterion("quarter_3 not in", values, "quarter3");
            return this;
        }

        public Criteria andQuarter3Between(Long value1, Long value2) {
            addCriterion("quarter_3 between", value1, value2, "quarter3");
            return this;
        }

        public Criteria andQuarter3NotBetween(Long value1, Long value2) {
            addCriterion("quarter_3 not between", value1, value2, "quarter3");
            return this;
        }

        public Criteria andQuarter4IsNull() {
            addCriterion("quarter_4 is null");
            return this;
        }

        public Criteria andQuarter4IsNotNull() {
            addCriterion("quarter_4 is not null");
            return this;
        }

        public Criteria andQuarter4EqualTo(Long value) {
            addCriterion("quarter_4 =", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4NotEqualTo(Long value) {
            addCriterion("quarter_4 <>", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4GreaterThan(Long value) {
            addCriterion("quarter_4 >", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4GreaterThanOrEqualTo(Long value) {
            addCriterion("quarter_4 >=", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4LessThan(Long value) {
            addCriterion("quarter_4 <", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4LessThanOrEqualTo(Long value) {
            addCriterion("quarter_4 <=", value, "quarter4");
            return this;
        }

        public Criteria andQuarter4In(List values) {
            addCriterion("quarter_4 in", values, "quarter4");
            return this;
        }

        public Criteria andQuarter4NotIn(List values) {
            addCriterion("quarter_4 not in", values, "quarter4");
            return this;
        }

        public Criteria andQuarter4Between(Long value1, Long value2) {
            addCriterion("quarter_4 between", value1, value2, "quarter4");
            return this;
        }

        public Criteria andQuarter4NotBetween(Long value1, Long value2) {
            addCriterion("quarter_4 not between", value1, value2, "quarter4");
            return this;
        }
    }
}